version: "3.8"

services:
  cosxl:
    container_name: cosxl
    image: maximofn/cosxl:1.0.1
    build: .
    runtime: nvidia
    network_mode: "host"
    volumes:
      - ./hub:/root/.cache/huggingface/hub
    tty: true
    stdin_open: true
